export const CENTRE_LIST_REQUEST = 'CENTRE_LIST_REQUEST'
export const CENTRE_LIST_SUCCESS = 'CENTRE_LIST_SUCCESS'
export const CENTRE_LIST_FAIL = 'CENTRE_LIST_FAIL'

export const CENTRE_DETAILS_REQUEST = 'CENTRE_DETAILS_REQUEST'
export const CENTRE_DETAILS_SUCCESS = 'CENTRE_DETAILS_SUCCESS'
export const CENTRE_DETAILS_FAIL = 'CENTRE_DETAILS_FAIL'